baseURL = "https://nklkhlr.github.io/"
languageCode = "en"
title = "Nikolai K\u00F6hler"
theme = "hugo-coder"
pagination.PageSizer = 6
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[markup]
	[markup.goldmark]
		[markup.goldmark.extensions]
			[markup.goldmark.extensions.passthrough]
			enable = true
			[markup.goldmark.extensions.passthrough.delimiters]
			block = [['\[', '\]'], ['$$', '$$']]
			inline = [['\(', '\)']]
	[markup.highlight]
	style = "catppuccin-mocha"

[params]
author = "Nikolai K\u00F6hler"
description = "Nikolai K\u00F6hler's personal website"
keywords = "blog,bioinformatics,metabolomics,spatial omics, optimal transport,tda"
info = ["Hi, I'm Nikolai, a Postdoctoral Researcher in the Velten lab at the University of Heidelberg working on Machine Learning for Spatial Omics data. Previously I did my doctorate in Computational Biology at the Technical University of Munich."]
avatarURL = "images/avatar.png"
footerContent = ""
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Enable mathjax
math = true
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5

[[params.social]]
name = "Mail"
icon = "fa fa-envelope fa-2x"
weight = 1
url = "mailto:nikolai.koehler@cos.uni-heidelberg.de"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/nklkhlr/"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 6
url = "https://bsky.app/profile/nklkhlr.bsky.social"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/nikolai-köhler-a79b3b300"

[[params.social]]
name = "Orcid"
icon = "fa-brands fa-orcid fa-2x"
weight = 4
url = "https://orcid.org/0000-0002-5103-883X"

[[params.social]]
name = "Scholar"
icon = "fa-brands fa-google-scholar fa-2x"
weight = 5
url = "https://scholar.google.com/citations?user=R-szd0IAAAAJ&hl=en&oi=ao"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Publications"
weight = 1
url = "publications/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "blog/"

[[languages.en.menu.main]]
name = "Talks"
weight = 3
url = "talks/"

[[languages.en.menu.main]]
name = "Teaching"
weight = 4
url = "teaching/"

[[languages.en.menu.main]]
name = "About"
weight = 5
url = "about/"

[[languages.en.menu.main]]
name = "CV"
weight = 6
url = "/cv/nikolaikoehler_academicCV2508.pdf"

