baseURL = "https://nklkhlr.github.io/"
languageCode = "en"
title = "Nikolai K\u00F6hler"
theme = "hugo-coder"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Nikolai K\u00F6hler"
description = "Nikolai K\u00F6hler's personal website"
keywords = "blog,bioinformatics,metabolomics"
info = ["Hi, I'm Nikolai, a PhD Student in Bioinformatics in the LipiTUM group at the Chair of Experimental Bioinformatics at the Technical University of Munich"]
avatarURL = "images/avatar.png"
footerContent = ""
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5

[[params.social]]
name = "Mail"
icon = "fa fa-envelope"
weight = 1
url = "mailto:nikolai.koehler@tum.de"


[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 2
url = "https://github.com/nklkhlr/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab"
weight = 3
url = "https://gitlab.lrz.com/nklkhlr/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 4
url = "https://twitter.com/nklkhlr/"

# [[params.social]]
# name = "LinkedIn"
# icon = "fa fa-linkedin"
# weight = 4
# url = "https://www.linkedin.com/in/johndoe/"

[[params.social]]
name = "Orcid"
icon = "fa fa-orcid"
weight = 5
url = "https://orcid.org/0000-0002-5103-883X"

[[params.social]]
name = "Scholar"
icon = "ai ai-google-scholar"
weight = 6
url = "https://scholar.google.com/citations?user=R-szd0IAAAAJ&hl=en&oi=ao"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "Publications"
weight = 1
url = "publications/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "blog/"

[[languages.en.menu.main]]
name = "Talks"
weight = 3
url = "talks/"

[[languages.en.menu.main]]
name = "Teaching"
weight = 3
url = "teaching/"

[[languages.en.menu.main]]
name = "About"
weight = 4
url = "about/"

